### ISSUE TITLE
Grill Cheese Recipe

### ISSUE THREAD

**Issue by zomeLua** [K1ngwing/FOSS-Cooking#1]
_**I think this is how you add recipes to the main repository I don't know I don't use Github**_

The best Grill Cheese Recipe I've ever made.

**Pre-proccess**
- Take 2 slices of bread
- Take 2 slices of cheese (gooy finish use American Cheese or processed cheese if you don't live in America. If you want regular healthy Cheese just use Mozzarella and Cheddar Cheese.)

**Cooking**
- Take a small pan and leave it on medium heat for 2-3 minutes
- Put one piece of bread on the pan
- Quickly put your choice or choices of cheese on the bread
- Finish it with the last piece of bread
- After about 2-3 minutes flip it
- Then after its brown take it out and put it in a plate

Put some parsley flakes on top to make it more appetizing (Don't need to do this if you are in a rush) 

_**And enjoy**_

**Comment by K1ngwing** [comment]
Added!
